apiVersion: v1
kind: Service
metadata:
  labels:
    app: On-Road-Vehicle-Breakdown-Assistance-System
    k8s-app: On-Road-Vehicle-Breakdown-Assistance-System
  name: on-road-vehicle-breakdown-assistance-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
  type: LoadBalancer
  selector:
    app: On-Road-Vehicle-Breakdown-Assistance-System